/* Hämtat från n8n-workflowet "Plan-vy · Intelligence-API", körningarna 1387 och 1396,
   2026-09-17 05:33 UTC. Kandidaternas kalkyl räknas i sidan ur
   indata med samma formel som backenden, så talen inte kan glida isär. */
const META = {
  period: "2026-09",
  generatedAt: "2026-09-17T05:33:15.908Z",
  currency: "SEK",
  vatRate: 0.25,
  sources: [
    ["sales", "Försäljning & annonskostnad", "real", "Live från Supabase (orders, order_lines, ad_spend)."],
    ["demand", "Efterfrågetrend", "real", "Egna månatliga ordrar över tid (v_product_period)."],
    ["candidates", "Research-kandidater", "real", "Sparade kandidater i product_candidates."],
    ["opportunity_score", "Opportunity Score", "computed", "Deterministisk vikt: lönsamhet 40% · marginal 25% · efterfrågetrend 35%."],
    ["ai_insights", "AI-verdict & analys", "ai-generated", "Genererat av språkmodell utifrån dina egna siffror (evidens-först)."],
    ["market_signals", "Kundröst / konkurrens / marknad", "ai-estimated", "Ingen fri live-API finns — AI-uppskattning, ej verifierad live-data."],
  ],
};

const OVERVIEW = {
  healthScore: 25, healthLabel: "Kritisk",
  breakdown: { poas: 56, margin: 0, winShare: 0 },
  kpis: {
    revenueExVat: 15200, orders: 70, units: 70, aov: 217.14, adSpend: 9400,
    contribution: 7850, netProfit: -1550, poas: 0.835, roas: 1.617,
    netMargin: -0.102, contribMargin: 0.5164, winners: 0, losers: 2,
    productCount: 2, candidateCount: 55,
  },
};

const PRODUCTS = [
  {
    name: "Posture Corrector", sku: "SPC-001", campaign: "Posture – Broad SE", status: "cut",
    f: { revenueExVat: 8000, revenueInclVat: 10000, orders: 40, units: 40, aov: 200, adSpend: 4200,
         cac: 105, contribution: 3200, contributionPerOrder: 80, netProfit: -1000,
         grossMargin: 0.4, poas: 0.762, roas: 1.905, breakEvenRoas: 2.5, returnRate: 0 },
    demand: { series: [{ month: "2026-09", orders: 40, units: 40, revenueExVat: 8000 }], monthsOfData: 1, momGrowth: null, trend: "unknown" },
    score: 63, scoreLabel: "Lovande", sb: { profitability: 51, margin: 100, demand: 50 },
    ai: {
      verdict: "Pausa",
      verdictReason: "POAS 0,762 är under break-even 1,00, roas 1,905 är också under breakEvenRoas 2,5, netProfit är -1 000 SEK och CAC 105 SEK äter upp contributionPerOrder på 80 SEK. Med endast 1 månad data och unknown demandTrend finns ingen evidens för att skala.",
      scoreSummary: "Opportunity Score 63 hålls uppe av 40% grossMargin och 40 orders, men pressas ned av POAS under break-even och negativ netProfit.",
      customerVoice: "AI-estimat: Kunderna verkar kunna acceptera produkten i volym, men ekonomin visar att pris eller annonskostnad inte räcker för lönsamhet.",
      competition: "AI-estimat: Troligen måttlig konkurrens där CPC/CAC blir för hög i förhållande till AOV 200 SEK.",
      market: "AI-estimat: Efterfrågan går inte att bedöma från given data; 1 månad data och okänd trend gör marknadsstorlek osäker.",
      opportunities: ["Sänk CAC genom bättre targeting eller lägre bud.","Testa högre AOV via bundle/upsell.","Optimera kreativet för att förbättra CVR."],
      risks: ["POAS 0,762 under break-even 1,00.","NetProfit -1 000 SEK på 40 orders.","Endast 1 månad data och okänd efterfrågetrend."],
    },
  },
  {
    name: "LED Sunset Lamp", sku: "LSL-002", campaign: "Sunset – Retargeting", status: "watch",
    f: { revenueExVat: 7200, revenueInclVat: 9000, orders: 30, units: 30, aov: 240, adSpend: 5200,
         cac: 173.33, contribution: 4650, contributionPerOrder: 155, netProfit: -550,
         grossMargin: 0.6458, poas: 0.894, roas: 1.385, breakEvenRoas: 1.55, returnRate: 0 },
    demand: { series: [{ month: "2026-09", orders: 30, units: 30, revenueExVat: 7200 }], monthsOfData: 1, momGrowth: null, trend: "unknown" },
    score: 66, scoreLabel: "Lovande", sb: { profitability: 60, margin: 100, demand: 50 },
    ai: {
      verdict: "Åtgärda CAC",
      verdictReason: "POAS 0,894 är under break-even 1,00, roas 1,385 ligger under breakEvenRoas 1,55 och netProfit är -550 SEK. GrossMargin är stark på 64,58%, men CAC 173,33 SEK är för hög relativt AOV 240 SEK.",
      scoreSummary: "Opportunity Score 66 stöds av hög grossMargin, men dras ned av att CAC överstiger contributionPerOrder-ekonomin.",
      customerVoice: "AI-estimat: Produkten verkar kunna sälja, men köpbeteendet tolererar inte dagens annonskostnad.",
      competition: "AI-estimat: Sannolikt konkurrensutsatt produktsegment där annonsering pressar marginalerna.",
      market: "AI-estimat: Intresse kan finnas, men utan trenddata går efterfrågan inte att kvantifiera.",
      opportunities: ["Sänk CAC genom snävare målgrupper eller bättre kreativa vinklar.","Testa prislyft eller bundle för att höja AOV.","Behåll endast om POAS förbättras över 1,00."],
      risks: ["POAS 0,894 under break-even 1,00.","NetProfit -550 SEK trots 64,58% grossMargin.","CAC 173,33 SEK är hög i relation till AOV 240 SEK."],
    },
  },
];

/* [severity, produkt, typ, text] */
const ALERTS = [
  ["critical", null, "portfolio", "Portföljen går med förlust denna period (netto -1550 kr)."],
  ["critical", "Posture Corrector", "poas", "Posture Corrector ligger långt under break-even (POAS 0.76)."],
  ["warning", "LED Sunset Lamp", "poas", "LED Sunset Lamp är under break-even (POAS 0.89)."],
];

/* [id, namn, anteckning, inköp, utpris, frakt, avgift, cpa, enheter, sparad, land]
   Belopp inkl moms i landets egen valuta. Kalkylen räknas fram i calcCandidate(). */
const RAW_CANDIDATES = [
["059d9947","Självrensande kattsandmatta med dubbel lager","Passar Sverige eftersom många kattägare bor i lägenhet och vill minska sand utanför lådan. Visuellt stark demo med tydlig problem/lösning och låg risk för returer.",74,249,39,7.47,145,1,"2026-09-17T05:32:24Z","SE"],
["adc4d9b7","Anti-glid matskål underlägg för hund och katt","Låg kostnad och lätt att förstå. Funkar bra i Sverige där många vill ha ett snyggt, tyst och städat matområde i kök eller hall.",18,169,26,5.07,100,1,"2026-09-17T05:32:24Z","SE"],
["898611c6","Automatisk laserleksak för katt med timer","Mer premium och därför högre CPA, men bra som test eftersom den är lätt att demonstrera och appellerar till kattägare som vill ha en enkel underhållningslösning hemma.",96,399,44,11.97,190,1,"2026-09-17T05:32:24Z","SE"],
["50ba556f","Luddborttagare för päls och möbler med självrengörande bas","Mycket relevant i svenska hem med soffor, filtar och pälsiga djur. Stark visuell payoff i före/efter-demo utan att lova mer än borttagning av hår.",31,199,31,5.97,125,1,"2026-09-17T05:32:24Z","SE"],
["68b332b8","Hopfällbar hundvattenskål i silikon med karbinhake","Bra impulse buy för hundägare som promenerar mycket. Enkelt att visa i video, låg inköpskostnad och lätt att paketera som frilufts-/vardagsprodukt.",22,179,28,5.37,110,1,"2026-09-17T05:32:24Z","SE"],
["e17eff2c","Antislip klädskydd för hängande skjortor och toppar","Bra för ordning i garderoben och fungerar visuellt när plagget annars glider av galgen. Prisnivån passar impulsköp i Sverige. Kan vinklas som 'ordning + mindre irritation' snarare än bara förvaring.",36,199,34,6,90,1,"2026-09-17T05:31:06Z","SE"],
["e8a0ace5","Bärbar klädstänk-/fläckborttagningspenna i set","Stark impulsprodukt i mode-nischen eftersom den löser ett konkret vardagsproblem på resande fot. Säljer bäst som 'räddare i väskan' för jobbet, middagar och pendling. Undvik medicinska eller kroppsliga claims.",29,199,28,6,80,1,"2026-09-17T05:31:06Z","SE"],
["8823ec57","Justerbar klädvårdsborste för päls och ludd","Svenska konsumenter köper gärna produkter som sparar pengar på att förlänga livslängden på kläder. Visuellt stark demo med ludd på mörka plagg, särskilt relevant för ull, fleece och vinterjackor.",33,219,31,6.6,105,1,"2026-09-17T05:31:06Z","SE"],
["be6960c3","Vintermössa med inbyggd LED-lampa","Sverige har lång mörk säsong, vilket gör produkten relevant och lätt att förstå. Funkar som impulsprodukt om den presenteras som smart vardagsaccessoar för promenader, hundrastning och pendling. Håll vinkeln praktisk, inte teknisk.",58,299,42,9,145,1,"2026-09-17T05:31:06Z","SE"],
["5b6ec4c0","Magnetisk scarf-/hattklämma för ytterplagg","Passar svensk vardagsstil och kallare klimat. En tydlig problemlösare för att hålla scarf, kofta eller halsduk på plats utan nålar. Bra för demo i rörlig bild och lätt att förstå på 2 sekunder.",42,249,39,7.5,115,1,"2026-09-17T05:31:06Z","SE"],
["bf1e506e","Push-up bars med halkskydd","Låg inköpskostnad och enkel visuell demo gör den lämplig för impulsköp. Säljer bäst med vinkel om bättre grepp, enklare variation och kompakt hemmaträning.",59,229,35,6.87,98,1,"2026-09-16T19:55:42Z","SE"],
["85b828ec","Portabel träningsmatta för hemmabruk","Bra som problemlösande produkt för svensk hemmaträning, särskilt i lägenhet där man vill ha en tydlig yta för yoga, stretch och kroppsvikt. Mindre impulsköp än små gadgets, men kan fungera med rätt visuell vinkling.",112,399,59,11.97,168,1,"2026-09-16T19:55:42Z","SE"],
["c81a021a","Motståndsband-set med dörrankare","Mycket stark kandidat i Sverige eftersom den är billig, lätt att skicka och passar breddad hemmaträning. Bra för demo med flera övningar och tydlig funktion: träning utan stora vikter.",94,299,39,8.97,132,1,"2026-09-16T19:55:42Z","SE"],
["c2dafae7","Maghjul med knästöd","Klassisk hemmaträningsprodukt som säljer via tydlig demo och enkel problemlösning: tränar kärna hemma utan maskiner. Fungerar bäst med nybörjarvänlig vinkel och upplevd kvalitet.",82,329,49,9.87,145,1,"2026-09-16T19:55:42Z","SE"],
["6a10ad3e","Kompakt hopprep med räknare","Bra impulsköp för hemmaträning, särskilt för enkel konditionsträning på liten yta. Visuellt lätt att demonstrera i kort video med fokus på enkelhet och platsbesparing.",68,249,39,7.47,115,1,"2026-09-16T19:55:42Z","SE"],
["d496b8fa","Electric Milk Frother Mug (USB-C)","Passar UK bra som vardagslyx till kaffe/tea lovers. Visuellt stark demo, låg friktionsköp, lätt att visa 'barista-at-home' utan medicinska claims.",8.5,29.99,3.2,0.9,12.5,1,"2026-09-16T19:20:27Z","GB"],
["5cf49528","Rechargeable Electric Salt and Pepper Grinders Set","Popular giftable gadget in the UK, especially for people who like a neat kitchen and easier everyday use. However, competition is higher and creative needs to feel premium and gift-worthy.",14.2,44.99,4.5,1.35,18.9,1,"2026-09-16T19:20:27Z","GB"],
["3c1cfa65","Automatic Pan Stirrer with Timer","Very demo-friendly and feels 'inventive', which can work well on Meta. Best angle in the UK is convenience for cooking sauces, risotto, gravy and soups without framing it as a premium appliance.",11.9,39.99,4.1,1.2,15.8,1,"2026-09-16T19:20:27Z","GB"],
["627cb8a7","Adjustable Pan Lid and Steam Vent Set","Useful for UK shoppers with mixed-size pans and limited storage. The appeal is convenience and kitchen tidiness, not a flashy gadget, so the ad needs a strong visual demonstration.",6.8,24.99,3.4,0.75,11.8,1,"2026-09-16T19:20:27Z","GB"],
["5132940f","Clip-On Pot Strainer Lid","Strong problem-solver for small UK kitchens where cupboard space is tight. Easy before/after demo, low price point, and a very clear 'why didn’t I buy this sooner?' angle.",3.1,19.99,2.9,0.6,9.5,1,"2026-09-16T19:20:27Z","GB"],
["8b0d63cd","Parvibrator med fjärrkontroll och app-styrning","Dyrare men ofta bättre AOV och stark differens via app/fjärr. Kan sälja på relation/kompispresent-vinkel. CPA tenderar högre eftersom målgruppen är mer konkurrensutsatt.",240,899,75,27,340,1,"2026-09-15T11:06:10Z","SE"],
["e6d6bc2a","Dubbeldesignad dildo av medicinsk silikon med sugkopp","Problem-/nyttodriven produkt med tydlig funktion och enkel demo via sugkopp och materialkänsla. Kan fungera bra om du säljer på kvalitet, stabilitet och 'handsfree'-vinkel.",175,649,70,19,290,1,"2026-09-15T11:06:10Z","SE"],
["9df592e2","Vattentät rabbit-vibrator med värmefunktion","Stark impulsköpsprodukt med tydlig demo (flera lägen, värme, vattentät). Bra hook: 'premiumkänsla hemma' och diskret leverans. Kan funka om kreativen är stilren och inte för explicit.",185,699,65,21,260,1,"2026-09-15T11:06:10Z","SE"],
["2c7c22c0","Diskret mini-vibrator i lipstick-format","Bra entry product för Meta Ads eftersom den är liten, diskret och lätt att förstå visuellt. Kan ge bättre CTR, men också fler priskänsliga köpare och lägre marginal.",95,349,50,10,180,1,"2026-09-15T11:06:10Z","SE"],
["f39b6dfd","Uppvärmd G-punktsstav med flexibelt huvud","Visuellt enkel att demonstrera med böjbart huvud och uppvärmning. Rimlig prispunkt för test. Vinkeln kan vara 'precision och komfort' snarare än hård säljkopia.",160,599,60,18,240,1,"2026-09-15T11:06:10Z","SE"],
["bcc6efcb","Rörelsestyrd LED-list för garderob och kök med USB-laddning","Enkel problemlösare med tydlig före/efter-effekt. Hook: \"ljus där du behöver det utan eldragning\". Bra för små ytor, bostadsrätter och hyrboenden.",92,329,45,9.87,145,1,"2026-09-15T08:52:15Z","SE"],
["df04db79","Magnetisk mobilhållare till bil med stark sugkopp och vridbart huvud","Lätt att demonstrera i video: håller telefonen stabilt på ojämna vägar. Bra hook: \"ingen mer telefon som ramlar\". Impulsköp med bred målgrupp.",78,279,42,8.37,170,1,"2026-09-15T08:52:15Z","SE"],
["028f3063","LED väckarklocka med trådlös laddning och temperaturvisning","Visuellt stark produkt som löser skrivbords-/sängbordstrassel. Hook: \"en produkt som ersätter flera\". Kan funka bra i UGC för hemmakontor och sovrum.",165,549,58,16.47,240,1,"2026-09-15T08:52:15Z","SE"],
["74538451","Mini Bluetooth-printer för etiketter och anteckningar","Visuellt demonstrerbar i kort video: printa etiketter från mobilen. Funkar för organisation, småföretag och studenter. Högre AOV men också högre CPA-risk.",240,799,69,23.97,330,1,"2026-09-15T08:52:15Z","SE"],
["1868deb3","USB-C hubb 6-i-1 med HDMI, kortläsare och laddning","Problemlösande för laptop-användare med få portar. Kan vinklas mot jobb, studier och resor. Mer rationell än impulsiv, men bra om kreativen visar \"saknade portar\"-problemet tydligt.",128,449,52,13.47,220,1,"2026-09-15T08:52:15Z","SE"],
["dc37669c","Heatless Curling Rod Set i satin","Stark visuellt före/efter, lätt att demonstrera i video. Bra hook: 'få mjuka lockar utan värme och skador'. Ofta låg frakt, men konkurrensen är hög.",38,149,29,4.47,85,1,"2026-09-15T08:50:34Z","SE"],
["1abac359","Reusable Makeup Remover Pads med tvättpåse","Miljövinkeln kan konvertera, särskilt som bundle med flera pads. Bra för 'spara pengar och minska engångsrondeller'. Inte lika starkt som hår/skin-tools men stabil testprodukt.",24,109,25,3.27,60,1,"2026-09-15T08:50:34Z","SE"],
["9aa13261","Silicone Scalp Massager Shampoo Brush","Visuellt tillfredsställande och enkel att förstå. Hook: bättre hårbottenkänsla, mer schampo-effekt, avkoppling i duschen. Marginalen är tunn men CPA kan vara låg.",19,89,23,2.67,48,1,"2026-09-15T08:50:34Z","SE"],
["a2fec317","Electric Eyebrow Trimmer med LED-ljus","Liten, impulsiv och tydligt problemlösande för snabb ansiktsvård. Bra vinkel: smärtfri, exakt, portabel. Kan fungera bra i korta demoannonser.",31,129,26,3.87,72,1,"2026-09-15T08:50:34Z","SE"],
["705e7f15","Silicone Face Ice Roller med refill-form","Tydlig problemlösare för puffighet och trötta morgonögon. Bra UGC-hook: '2 minuter på morgonen för fräschare look'. Risk: lägre AOV och lätt att price-competa.",22,99,24,2.97,55,1,"2026-09-15T08:50:34Z","SE"],
["d9c9b128","Magnetisk korthållare till mobil med plånboksfunktion","Bra för Meta Ads eftersom den kan visas på en iPhone/Android med snabb före-efter-demo. Stark hook: 'slipp plånboken, ha korten på mobilen'.",68,249,32,7.5,145,1,"2026-09-14T22:57:19Z","SE"],
["9ae76b44","Tunn reseplånbok med passficka och RFID-skydd","Visuellt demonstrerbar för resor och vardagsbruk, särskilt mot säkerhets- och ordningsvinklar. Bra vid säsongstoppar, men inte alltid stark nog att bära hög CPA året runt.",74,279,36,8.4,160,1,"2026-09-14T22:57:19Z","SE"],
["d0614843","Herrplånbok i äkta läder med pop-up kortfack","Klassisk produkt med högre upplevt värde, men konkurrensen är hård. Kan funka med premiumvinkel och gåvotema, men marginalen blir mer pressad.",98,349,39,10.5,190,1,"2026-09-14T22:57:19Z","SE"],
["87edf345","Slimmad anti-tjuv plånbok med dragkedja och myntfack","Lösningsorienterad för personer som vill ha säkrare förvaring och bättre organisation. Inte lika 'wow', men kan fungera med praktiska hooks kring vardagskaos och fickvänlighet.",82,289,35,8.7,165,1,"2026-09-14T22:57:19Z","SE"],
["4ee0a66d","RFID-blocker tunn plånbok i aluminium","Tydlig problemdriven vinkel: skyddar kort, är minimalistisk och lätt att demonstrera i video. Funkar ofta som impulsköp för män 25–55.",55,199,29,6,120,1,"2026-09-14T22:57:19Z","SE"],
["cbfe5e9a","Hopfällbar silikondurkslag i rostfritt handtag","Visuellt enkel produkt som löser förvaring i små kök. Bra hook: ’sparar skåpsplats’. Inte den mest sexiga produkten, så kräver starka kreativa.",42,159,35,5,78,1,"2026-09-14T22:56:57Z","SE"],
["d6bfaca8","Vakuumpump för vinflaska med 4 återanvändbara korkar","Bra present- och impulsprodukt med tydlig användning efter middagar. Kan fungera med kvälls- och helg-customer, men säljcykeln är smalare och CPA kan bli hög.",64,249,40,7,112,1,"2026-09-14T22:56:57Z","SE"],
["3c701278","Silicone air fryer liner med hög kant, 2-pack","Lätt att demonstrera: mindre rengöring och mindre fett i airfryern. Bra volymprodukt, men ofta prispressad och kräver paket/uppsidesförklaring.",36,149,34,4,72,1,"2026-09-14T22:56:57Z","SE"],
["d8117098","Antislip-matta för skärbräda med sugproppar","Problemlösande för halkande skärbrädor och bättre säkerhet. Bra UGC-hook med före/efter, men låg impulsnivå och kräver pedagogisk annons.",31,129,32,4,68,1,"2026-09-14T22:56:57Z","SE"],
["c77c8784","Elektrisk minihackare för vitlök och lök, uppladdningsbar","Tydlig demo: hackar vitlök/lök på sekunder. Funkar bra för ’slipp tårar och kladd’-vinkel, men konkurrensen är hög och returrisken medel.",58,199,39,6,95,1,"2026-09-14T22:56:57Z","SE"],
["bd2fd38d","Trådlös vägglampa med uppladdningsbart batteri och touch-dimmer","Kan funka för hyresgäster och folk som inte vill dra el. Visuellt stark med enkel montering utan borrning och mysig kvällsbelysning.",132,449,49,13,210,1,"2026-09-14T22:54:55Z","SE"],
["369a041b","Varmvit dimbar LED-girlanga för balkong och sovrum","Impulsvänlig inredningsprodukt med starkt visuellt uttryck. Fungerar bra i kreativa ads med mysig transformation av balkong, sovrum eller uteplats.",92,299,45,9,160,1,"2026-09-14T22:54:55Z","SE"],
["1231e9c8","Solcellsdriven utomhusvägglampa med rörelsesensor","Problemlösande för entré, garage och stuga utan eldragning. Bra visuell demo kvällstid med rörelsestyrt ljus och säkerhetsvinkel.",118,399,59,12,185,1,"2026-09-14T22:54:55Z","SE"],
["4d039e06","LED-spegelbelysning med självhäftande remsa för sminkbord och badrumsspegel","Låg tröskel och tydlig användningsnytta för smink/​hudvård. Meta-vänlig hook är bättre ljus för makeup på några sekunder, enkel före/efter.",64,199,35,6,110,1,"2026-09-14T22:54:55Z","SE"],
["0121df66","Laddningsbar rörelsesensor-lampa för garderob och kök under skåp","Bra impulsköp eftersom den löser ett tydligt problem: mörka garderober, köksskåp och hallskåp. Lätt att demonstrera i kort video med före/efter och rörelsesensor.",78,249,39,8,145,1,"2026-09-14T22:54:55Z","SE"],
["70e770a8","Vikbar diskho-sil / sink strainer i rostfritt stål","Problemlösande för matrester i vasken och enkel före/efter-demo. Funkar bra med vinkeln 'stoppa stopp i avloppet'.",42,189,29,5.7,110,1,"2026-09-14T22:54:50Z","SE"],
["8eb9d1ce","Automatisk kryddburksöppnare för glasburkar","Problemlösande för personer med svag handstyrka och lätt att visa i video. Mer nischad, men tydlig pain-point och bra present-vinkel.",84,299,34,9,175,1,"2026-09-14T22:54:50Z","SE"],
["7a71019e","Justerbar kylskåpsorganisatör med utdragbar låda","Visuellt starkt för 'före/efter'-organisering i kylskåpet. Kan funka men är mer konkurrensutsatt och kräver stark creative.",96,329,39,9.9,190,1,"2026-09-14T22:54:50Z","SE"],
["d5c093f4","Elektrisk mjölkskummare handhållen USB-uppladdningsbar","Impulsköp med tydlig demo: snabb skumning av kaffe på sekunder. Bra för reel/video med latte-inspirerad vardagslyx.",68,249,28,7.5,145,1,"2026-09-14T22:54:50Z","SE"],
["41df9aba","Mikrovågslock med ångventil i silikon","Lätt att demonstrera visuellt: stänkfritt, återanvändbart och sparar tid vid uppvärmning. Bra hook: 'slipp mikrovågsskrubbet'.",18,149,22,4.5,85,1,"2026-09-14T22:54:50Z","SE"],
];

/* Annonsupplägg per kandidat. Egen kreativ, genererad av modellen — sökningen
   i Metas publika annonsbibliotek är till för att se vad som redan går. */
const AD_PLANS = {
  "059d9947": { q: "cat litter mat",
    angle: "Renare golv utan extra jobb – enkel vardagslösning för kattägare i hem med begränsat utrymme.", hook: "Trött på kattsand över hela golvet?", format: "UGC-demo 15 s, vertikal 9:16",
    script: ["0-3 s: Visa kattsand spridas utanför lådan på ett vanligt golv.","3-7 s: Lägg ut mattan och visa hur sanden faller ner i lagren.","7-11 s: Lyft mattan och skaka tillbaka sanden i lådan.","11-15 s: Visa ett renare golv och produkten i användning vid kattlådan."],
    audience: "Kattägare i Sverige, 25-54 år, intressen: katt, kattfoder, kattlåda, husdjur, hemstädning, inredning.", primaryText: "Mindre sand på golvet och enklare städning runt kattlådan. En smart lösning för kattägare som vill hålla hemmet lite renare.", headline: "Mindre sand på golvet" },
  "adc4d9b7": { q: "pet bowl mat",
    angle: "Mindre spill, mindre ljud och ett renare matområde.", hook: "Skjuter matskålen runt överallt?", format: "UGC-demo 10 s, vertikal 9:16",
    script: ["0-2 s: Visa skålar som glider runt på golvet.","2-5 s: Lägg ut underlägget och placera skålarna ovanpå.","5-8 s: Visa hund eller katt äta medan underlägget ligger still.","8-10 s: Närbild på enkel avtorkning och ren yta."],
    audience: "Hund- och kattägare i Sverige, 25-55 år, intressen: husdjursprodukter, kök, hemorganisering, städning, småhus/lägenhet.", primaryText: "Håll matplatsen mer organiserad och minska att skålarna glider runt. En liten detalj som gör vardagen enklare.", headline: "Skålar som stannar på plats" },
  "898611c6": { q: "cat laser toy",
    angle: "Självspelande kattunderhållning för hemma-bruk.", hook: "Din katt kommer att jaga det här i timmar.", format: "Demo med katt i hemmet 15 s, vertikal 9:16",
    script: ["0-3 s: Visa katten som sitter uttråkad på golvet.","3-6 s: Starta leksaken och visa laserbanan röra sig.","6-11 s: Klipp till katten som följer ljuset runt rummet.","11-15 s: Visa timer/auto-läge och leksaken på ett sidobord."],
    audience: "Kattägare i Sverige, 20-50 år, intressen: katt, kattlek, husdjur, heminredning, smarta hem, djurtillbehör.", primaryText: "En enkel leksak som ger katten något att jaga hemma. Smidig när du vill ha en lättskött lösning för lekstunder.", headline: "Automatisk lek för katten" },
  "50ba556f": { q: "pet hair remover",
    angle: "Snabb städning av djurhår från textilier och möbler.", hook: "Hundhår i soffan igen?", format: "Före/efter split screen 12 s",
    script: ["0-3 s: Visa en soffa full av hund- eller katthår.","3-6 s: Dra verktyget över tyget i långsamma drag.","6-9 s: Visa hår samlas i verktyget och i basen.","9-12 s: Visa ren soffa och enkel tömning av behållaren."],
    audience: "Hund- och kattägare i Sverige, 25-60 år, intressen: städning, hemmet, hund, katt, inredning, textilier.", primaryText: "Ett enkelt sätt att samla upp djurhår från soffor, filtar och bilsäten. Praktiskt för hem där päls alltid verkar hitta tillbaka.", headline: "Tar upp djurhår snabbt" },
  "68b332b8": { q: "collapsible dog bowl",
    angle: "På språng-lösning för hundpromenader, bilresor och utflykter.", hook: "Glöm vattenflaskan på promenaden.", format: "UGC-demo 12 s, vertikal 9:16",
    script: ["0-2 s: Visa hund och ägare ute på promenad utan skål.","2-5 s: Fäll snabbt ut skålen med en hand.","5-8 s: Häll i vatten och visa hunden dricka.","8-12 s: Fäll ihop, klicka fast i koppel/väska och visa hur liten den blir."],
    audience: "Hundägare i Sverige, 20-55 år, intressen: hundpromenad, friluftsliv, vandring, hundträning, hundtillbehör.", primaryText: "En enkel skål du kan ta med överallt. Perfekt för promenader, resor och spontana äventyr med hunden.", headline: "Smart skål för promenader" },
  "e17eff2c": { q: "hanging clips",
    angle: "Gör garderoben mer organiserad: slipp att skjortor, toppar och tunna plagg halkar av galgen.", hook: "Glider dina plagg alltid av galgen?", format: "Problem-lösning demo 12 s, vertikal 9:16",
    script: ["0–3 s: Visa ett plagg som faller av en vanlig galge.","3–6 s: Visa produkten fäst på galgen i närbild.","6–9 s: Häng upp samma typ av plagg och visa att det sitter bättre.","9–12 s: Slutbild på en mer organiserad garderob med kort text-overlay."],
    audience: "Kvinnor och män 20–45 i Sverige, intressen: hemorganisation, garderob, mode, minimalism, shopping, inredning.", primaryText: "Små lösningar gör garderoben mycket enklare att leva med. Det här hjälper tunna plagg att sitta bättre på galgen och minskar onödigt strul.", headline: "Slipp plagg som glider" },
  "e8a0ace5": { q: "stain remover pen",
    angle: "Nödlösning för olyckor med kaffe, smink, mat och vardagsfläckar på kläder.", hook: "Spillde du på kläderna precis innan du skulle gå?", format: "UGC-demo 15 s, vertikal 9:16",
    script: ["0–2 s: Visa en liten fläck på en skjorta eller topp.","2–6 s: Använd pennan direkt på fläcken i närbild.","6–10 s: Torka av och visa ett renare intryck.","10–15 s: Visa att den får plats i väska/jackficka och avsluta med CTA."],
    audience: "Kvinnor och män 18–44 i Sverige, intressen: mode, arbete, pendling, resor, studentliv, väskor, vardagsaccessoarer.", primaryText: "Bra att ha i väskan när något går fel. En liten klädvårdslösning för vardagens spill, snabbt och enkelt.", headline: "Räddaren i väskan" },
  "8823ec57": { q: "lint remover",
    angle: "Gör kläderna mer användbara längre: ta bort ludd, hår och fnas från vardagsplagg snabbt.", hook: "Ludd på kläderna förstör hela looken, eller hur?", format: "Före/under/efter demo 14 s, vertikal 9:16",
    script: ["0–3 s: Visa ett mörkt plagg med synligt ludd och hår.","3–7 s: Dra borsten över tyget i en tydlig närbild.","7–11 s: Visa skillnaden på samma plagg i bättre ljus.","11–14 s: Avsluta med garderob/klädvård-vinkel och enkel CTA."],
    audience: "Kvinnor och män 20–55 i Sverige, intressen: klädvård, mode, tvätt, hemmet, städning, ull, pälsdjursägare.", primaryText: "Ett enkelt sätt att fräscha upp dina favoritplagg utan krångel. Bra för mörka kläder, ull och vardagsplagg som lätt drar åt sig ludd.", headline: "Fräscha upp kläderna" },
  "be6960c3": { q: "led beanie",
    angle: "Smart vinteraccessoar för mörka kvällar: värme + synlighet + händer fria i ett enda plagg.", hook: "En mössa som lyser när du behöver det?", format: "UGC-demo 15 s, vertikal 9:16",
    script: ["0–2 s: Mörk kvällspromenad, personen letar i väskan eller håller i mobilens ficklampa.","2–5 s: Sätt på mössan och tänd lampan med en tydlig knapptryckning.","5–10 s: Visa användning vid hundpromenad, cykel eller väg till bilen.","10–15 s: Close-up på lampan och enkel avslutande produktbild."],
    audience: "Kvinnor och män 18–55 i Sverige, intressen: outdoor, friluftsliv, hundägare, promenader, vinterkläder, pendling, arbete utomhus.", primaryText: "Perfekt för mörka morgnar och kvällar. En enkel vintermössa med inbyggd lampa när du vill se bättre och slippa hålla i något extra.", headline: "Smart mössa för mörkret" },
  "5b6ec4c0": { q: "scarf clip",
    angle: "Praktisk stil-fix för vardag och ytterplagg: se elegant ut utan att plagget glider isär eller behöver justeras hela tiden.", hook: "Trött på att ytterplagget glider isär hela dagen?", format: "UGC-demo 15 s, vertikal 9:16",
    script: ["0–2 s: Visa en scarf/kofta som öppnar sig och stör en outfit.","2–6 s: Demonstrera hur klämman sätts på diskret och håller tyget på plats.","6–11 s: Visa två olika outfits med samma accessoar, nära detaljbild på finishen.","11–15 s: Avsluta med enkel CTA: snabb lösning för vardagsstil och lager-på-lager."],
    audience: "Kvinnor 25–54 i Sverige, intressen: mode, dammode, skandinaviskt mode, kapselgarderob, stil, accessories, online shopping.", primaryText: "En liten detalj som gör stor skillnad i vardagen. Håll scarf, kofta eller ytterplagg på plats och få en renare look på några sekunder.", headline: "Håll plagget på plats" },
  "bf1e506e": { q: "push up bars",
    angle: "Bättre grepp och enklare armhävningar hemma", hook: "Vanliga armhävningar känns tråkiga? Testa en enklare setup hemma.", format: "Före/efter split screen 12 s, vertikal 9:16",
    script: ["0–3 s: Visa golv-armhävningar direkt mot golvytan och text om grepp och komfort.","3–6 s: Byt till push-up bars och visa hur händerna kommer upp från golvet.","6–9 s: Snabb demo av fler vinklar och övningar på samma produkt.","9–12 s: Close-up på halkskydd och enkel förvaring under soffa eller säng."],
    audience: "Män 18–45 år i Sverige, intressen: styrketräning, calisthenics, hemmaträning, armhävningar, fitness, bodyweight training.", primaryText: "Ett enkelt tillbehör som gör hemmaträningen mer praktisk utan att ta plats. Bra för dig som vill träna överkropp hemma med stabilt grepp.", headline: "Stabilare armhävningar hemma" },
  "85b828ec": { q: "exercise mat",
    angle: "Skapa en tydlig träningsyta hemma på sekunder", hook: "Det tar bara några sekunder att göra golvet redo för träning.", format: "UGC-demo 15 s, vertikal 9:16",
    script: ["0–3 s: Visa ett vanligt vardagsrumsgolv och text om att träna utan att flytta möbler.","3–7 s: Rulla ut mattan och visa storleken samt greppet mot golvet.","7–11 s: Demonstrera stretch, core och lätt kroppsviktsträning på mattan.","11–15 s: Rulla ihop den snabbt och visa enkel förvaring bakom dörr eller soffa."],
    audience: "Kvinnor och män 20–45 år i Sverige, intressen: yoga, pilates, hemmaträning, mobility, stretching, fitness, lägenhetsliv.", primaryText: "Gör hemmaträningen enklare med en matta som skapar en tydlig plats för passet. Praktisk när du vill komma igång snabbt och hålla ytan ordnad.", headline: "Redo för träning på sekunder" },
  "c81a021a": { q: "resistance bands",
    angle: "Ett helt hemmagym i en påse", hook: "Det här lilla setet kan ersätta halva gymväskan hemma.", format: "UGC-demo 18 s, vertikal 9:16",
    script: ["0–3 s: Visa alla band uppställda på ett bord med text om enkel hemmaträning.","3–8 s: Snabba klipp på rodd, press och benövningar med samma set.","8–13 s: Visa dörrankaret och hur det fästs i en vanlig dörr.","13–18 s: Packa ihop allt i påsen och avsluta med CTA om enkel träning hemma."],
    audience: "Vuxna 20–50 år i Sverige, intressen: hemmaträning, styrketräning, pilates, yoga, rehab-träning, fitness, träningsband.", primaryText: "Ett kompakt träningsset för hemmabruk som är lätt att ta fram, lätt att förstå och lätt att förvara. Perfekt när du vill träna med motstånd utan stora redskap.", headline: "Hemmagym i en påse" },
  "c2dafae7": { q: "ab wheel",
    angle: "En enkel core-produkt för hemmaträning", hook: "Det här är ett av de enklaste sätten att göra hemmaträningen mer effektiv.", format: "UGC-demo 20 s, vertikal 9:16",
    script: ["0–3 s: Visa produkten direkt på golvet med text om hemmaträning utan maskinpark.","3–8 s: Demonstrera rullningen framåt och tillbaka, gärna med knästöd för att signalera användarvänlighet.","8–14 s: Visa hur den packas undan snabbt och fungerar på liten yta.","14–20 s: Close-up på handtag, hjul och knäskydd, avsluta med enkel CTA."],
    audience: "Män och kvinnor 18–44 år i Sverige, intressen: styrketräning, hemmagym, calisthenics, fitness, core-träning, träningsutrustning.", primaryText: "Vill du ha en liten träningsprodukt som faktiskt används hemma? Maghjulet är kompakt, enkelt att förstå och passar bra i ett snabbt hemmapass.", headline: "Kompakt core-träning hemma" },
  "6a10ad3e": { q: "jump rope",
    angle: "Snabb kondition hemma utan att ta plats", hook: "Du behöver inte ett gym för att få upp pulsen hemma.", format: "UGC-demo 15 s, vertikal 9:16",
    script: ["0–3 s: Visa ett stökigt vardagsrum och texten om att träna hemma utan dyr utrustning.","3–7 s: Snabb demo av hopprepet, hur räknaren visar antal hopp och hur lätt det är att använda.","7–11 s: Klipp med användning i hall/vardagsrum och när produkten läggs i en låda eller väska.","11–15 s: Close-up på funktioner och call to action: enkel start, liten plats, beställ idag."],
    audience: "Vuxna 20–45 år i Sverige, intressen: hemmaträning, kondition, fitness, HIIT, yoga, träningsappar, fitness-gadgets.", primaryText: "En enkel träningsgrej som funkar hemma, kräver minimal plats och är lätt att ta fram när du vill få in ett snabbt pass. Perfekt för dig som vill hålla igång utan att bygga ett hemmagym.", headline: "Träna hemma på liten yta" },
  "d496b8fa": { q: "milk frother",
    angle: "Make café-style drinks at home in seconds", hook: "I didn’t expect a £30 gadget to make this much difference to my morning coffee.", format: "UGC-demo 15 s, vertical 9:16",
    script: ["0-3s: Close-up of flat milk in a mug; text overlay: 'Why does home coffee never feel like this?'","3-7s: Show the frother switched on in the mug, creating foam quickly.","7-11s: Pour the frothed milk into coffee; capture the texture and sound.","11-15s: Final shot of the finished drink beside a kitchen counter; CTA: 'Upgrade your routine'."],
    audience: "UK coffee drinkers, home workers, instant coffee buyers, interests: coffee, home brewing, kitchen gadgets, Starbucks, Nespresso", primaryText: "Turn your daily coffee into a café-style drink at home in seconds. A simple kitchen upgrade for anyone who wants better mornings without the café price tag.", headline: "Café Coffee at Home" },
  "5cf49528": { q: "electric grinder",
    angle: "A cleaner, easier upgrade for everyday seasoning", hook: "These are the kitchen upgrade I didn’t know I wanted until I used them.", format: "Premium UGC demo 15 s, vertical 9:16",
    script: ["0-3s: Show manual grinder twisting effortlessly replaced by a one-button electric grinder.","3-7s: Close-up of fresh seasoning falling onto food.","7-11s: Show the set on a clean dining table or beside the hob.","11-15s: End with both grinders charging neatly; text overlay: 'Simple, tidy, giftable'."],
    audience: "Gift buyers, home cooks, new homeowners, interests: kitchenware, home gifts, cooking, dining, home decor", primaryText: "A simple everyday upgrade that looks great on the counter and works with one touch. A practical gift idea for any UK kitchen.", headline: "Easy One-Touch Grinding" },
  "3c1cfa65": { q: "automatic stirrer",
    angle: "Hands-free stirring for busy home cooks", hook: "This is the closest thing to having an extra hand in the kitchen.", format: "Kitchen demo 20 s, vertical 9:16",
    script: ["0-4s: Show sauce or risotto simmering while the cook steps away briefly.","4-8s: Place the automatic stirrer in the pan and switch it on.","8-14s: Show consistent stirring while the person preps another ingredient.","14-20s: End with a smooth finished dish and text overlay: 'Stay focused on the rest of dinner'."],
    audience: "Busy parents, home cooks, meal prep buyers, interests: cooking, kitchen gadgets, air fryers, recipe content, home convenience", primaryText: "Keep things moving while you prep the rest of dinner. A clever kitchen helper for sauces, soups and slow-cook style recipes.", headline: "Hands-Free Stirring" },
  "627cb8a7": { q: "adjustable lid",
    angle: "One lid that fits more than one pan", hook: "If your cupboard is full of random lids, this solves the chaos.", format: "UGC kitchen hack demo 18 s, vertical 9:16",
    script: ["0-4s: Show a messy stack of different pan lids sliding around in a cupboard.","4-8s: Reveal the adjustable lid and demonstrate it fitting two different pans.","8-13s: Show steam vent in use while cooking on the hob.","13-18s: Finish with a neat cupboard shot and text overlay: 'Less clutter, more use'."],
    audience: "UK homeowners, renters, organisation shoppers, interests: kitchen organisation, home improvement, cooking, compact living", primaryText: "Replace the random stack of lids with one adjustable solution. A smart kitchen buy for everyday cooking and tidier storage.", headline: "One Lid, More Pans" },
  "5132940f": { q: "pot strainer",
    angle: "Stops spills and saves space in small kitchens", hook: "This tiny kitchen tool saves me from making a mess every single night.", format: "Problem-solution demo 12 s, vertical 9:16",
    script: ["0-3s: Show someone trying to drain pasta with a lid slipping off; messy water splash.","3-6s: Introduce the clip-on strainer lid clipped onto the pan.","6-9s: Pour out water smoothly with no extra colander.","9-12s: End on tidy countertop and pan; text overlay: 'One less thing to wash'."],
    audience: "Home cooks, renters, students, small flat kitchens, interests: cooking, meal prep, kitchen organisation, homeware", primaryText: "A simple way to strain pasta, veg or potatoes without reaching for a bulky colander. Ideal for smaller UK kitchens where space and cleanup both matter.", headline: "Strain Without the Mess" },
  "8b0d63cd": { q: "parvibrator fjärrkontroll app" },
  "e6d6bc2a": { q: "dubbeldesignad dildo medicinsk" },
  "9df592e2": { q: "vattentät rabbit vibrator" },
  "2c7c22c0": { q: "diskret mini vibrator" },
  "f39b6dfd": { q: "uppvärmd punktsstav flexibelt" },
  "bcc6efcb": { q: "rörelsestyrd led list" },
  "df04db79": { q: "magnetisk mobilhållare bil" },
  "028f3063": { q: "led väckarklocka trådlös" },
  "74538451": { q: "mini bluetooth printer" },
  "1868deb3": { q: "usb hubb hdmi" },
  "dc37669c": { q: "heatless curling rod" },
  "1abac359": { q: "reusable makeup remover" },
  "9aa13261": { q: "silicone scalp massager" },
  "a2fec317": { q: "electric eyebrow trimmer" },
  "705e7f15": { q: "silicone face ice" },
  "d9c9b128": { q: "magnetisk korthållare mobil" },
  "9ae76b44": { q: "tunn reseplånbok passficka" },
  "d0614843": { q: "herrplånbok äkta läder" },
  "87edf345": { q: "slimmad anti tjuv" },
  "4ee0a66d": { q: "rfid blocker tunn" },
  "cbfe5e9a": { q: "hopfällbar silikondurkslag rostfritt" },
  "d6bfaca8": { q: "vakuumpump för vinflaska" },
  "3c701278": { q: "silicone air fryer" },
  "d8117098": { q: "antislip matta för" },
  "c77c8784": { q: "elektrisk minihackare för" },
  "bd2fd38d": { q: "trådlös vägglampa uppladdningsbart" },
  "369a041b": { q: "varmvit dimbar led" },
  "1231e9c8": { q: "solcellsdriven utomhusvägglampa rörelsesensor" },
  "4d039e06": { q: "led spegelbelysning självhäftande" },
  "0121df66": { q: "laddningsbar rörelsesensor lampa" },
  "70e770a8": { q: "vikbar diskho sil" },
  "8eb9d1ce": { q: "automatisk kryddburksöppnare för" },
  "7a71019e": { q: "justerbar kylskåpsorganisatör utdragbar" },
  "d5c093f4": { q: "elektrisk mjölkskummare handhållen" },
  "41df9aba": { q: "mikrovågslock ångventil silikon" },
};

const AI = {
  healthNarrative: "Portföljen är svag: revenueExVat 15 200 SEK men netProfit -1 550 SEK, netMargin -10,2% och POAS 0,835 under break-even 1,00. Båda aktiva produkterna ligger under lönsamhetströskeln (Posture Corrector POAS 0,762 och LED Sunset Lamp POAS 0,894), vilket förklarar healthScore 25 och 0 vinnare.",
  recommendations: [
    { title: "Pausa eller kraftigt begränsa Posture Corrector", detail: "Produkten är tydligt olönsam med POAS 0,762 < 1,00, netProfit -1 000 SEK, CAC 105 SEK och contributionPerOrder 80 SEK. Med endast 1 månad data finns ingen trend som motiverar fortsatt volym.", priority: "high", product: "Posture Corrector", links: [["Posture Corrector", "SPC-001", "product"]] },
    { title: "Åtgärda eller pausa LED Sunset Lamp om förbättring uteblir", detail: "LED Sunset Lamp ligger också under break-even med POAS 0,894, roas 1,385 under breakEvenRoas 1,55 och netProfit -550 SEK. Marginen ser bättre ut (grossMargin 64,58%), men CAC 173,33 SEK äter upp ekonomin.", priority: "high", product: "LED Sunset Lamp", links: [["LED Sunset Lamp", "LSL-002", "product"]] },
    { title: "Flytta budget till testbara kandidater med POAS > 1,20", detail: "Flera kandidater har förväntad POAS tydligt över break-even, t.ex. Automatic Pan Stirrer with Timer 1,442, Mini Bluetooth-printer 1,412, Clip-On Pot Strainer Lid 1,409 och Vattentät rabbit-vibrator med värmefunktion 1,646. Dessa bör prioriteras före nuvarande förlorare.", priority: "medium", product: "Kandidater", links: [["Kandidater", "", "research"]] },
    { title: "Undvik kandidater under break-even direkt", detail: "Kandidater som Magnetisk mobilhållare till bil 0,886, Heatless Curling Rod Set 0,912, Silicone Face Ice Roller 0,910 och flera andra ligger under 1,00 i expectedPoas och bör inte få budget före starkare alternativ.", priority: "medium", product: "Kandidater", links: [["Kandidater", "", "research"]] },
  ],
  risks: [
    { title: "Negativ portföljekonomi fortsätter", detail: "Med netProfit -1 550 SEK, netMargin -10,2% och POAS 0,835 under break-even finns risk att fortsatt spend förstärker förlusten om inte sämsta produkterna stoppas.", severity: "high", links: [] },
    { title: "För lite datapunkter för att skilja brus från signal", detail: "Båda aktiva produkter har monthsOfData 1 och demandTrend unknown, vilket gör det svårt att säkert avgöra om låg POAS är strukturell eller tillfällig.", severity: "medium", links: [] },
    { title: "CAC-nivåer över driver lönsamheten ned", detail: "Posture Corrector har CAC 105 SEK på AOV 200 SEK och LED Sunset Lamp CAC 173,33 SEK på AOV 240 SEK, vilket lämnar för lite marginal efter annonsering.", severity: "high", links: [] },
  ],
  nextActions: ["Pausa eller sänk spend på Posture Corrector direkt och följ POAS dagligen tills den antingen passerar 1,00 eller stängs.","Testa en kontrollerad budgetminskning på LED Sunset Lamp och verifiera om ROAS/POAS förbättras vid lägre CAC.","Starta 3-5 nya småskaliga tester från kandidater med expectedPoas över 1,20, med prioritet på Automatic Pan Stirrer with Timer, Mini Bluetooth-printer och Vattentät rabbit-vibrator med värmefunktion.","Exkludera kandidater med expectedPoas under 1,00 från budget tills högre-POAS tester är verifierade."],
};
